# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arattel/CLionProjects/Syzonov_conting_words_in_file_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arattel/CLionProjects/Syzonov_conting_words_in_file_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arattel/CLionProjects/Syzonov_conting_words_in_file_2/CMakeFiles /home/arattel/CLionProjects/Syzonov_conting_words_in_file_2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arattel/CLionProjects/Syzonov_conting_words_in_file_2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Counting_words_in_file

# Build rule for target.
Counting_words_in_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Counting_words_in_file
.PHONY : Counting_words_in_file

# fast build rule for target.
Counting_words_in_file/fast:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/build
.PHONY : Counting_words_in_file/fast

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/config.cpp.s
.PHONY : config.cpp.s

conveyor.o: conveyor.cpp.o

.PHONY : conveyor.o

# target to build an object file
conveyor.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/conveyor.cpp.o
.PHONY : conveyor.cpp.o

conveyor.i: conveyor.cpp.i

.PHONY : conveyor.i

# target to preprocess a source file
conveyor.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/conveyor.cpp.i
.PHONY : conveyor.cpp.i

conveyor.s: conveyor.cpp.s

.PHONY : conveyor.s

# target to generate assembly for a file
conveyor.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/conveyor.cpp.s
.PHONY : conveyor.cpp.s

count_words.o: count_words.cpp.o

.PHONY : count_words.o

# target to build an object file
count_words.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/count_words.cpp.o
.PHONY : count_words.cpp.o

count_words.i: count_words.cpp.i

.PHONY : count_words.i

# target to preprocess a source file
count_words.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/count_words.cpp.i
.PHONY : count_words.cpp.i

count_words.s: count_words.cpp.s

.PHONY : count_words.s

# target to generate assembly for a file
count_words.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/count_words.cpp.s
.PHONY : count_words.cpp.s

decompress_list.o: decompress_list.cpp.o

.PHONY : decompress_list.o

# target to build an object file
decompress_list.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/decompress_list.cpp.o
.PHONY : decompress_list.cpp.o

decompress_list.i: decompress_list.cpp.i

.PHONY : decompress_list.i

# target to preprocess a source file
decompress_list.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/decompress_list.cpp.i
.PHONY : decompress_list.cpp.i

decompress_list.s: decompress_list.cpp.s

.PHONY : decompress_list.s

# target to generate assembly for a file
decompress_list.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/decompress_list.cpp.s
.PHONY : decompress_list.cpp.s

input.o: input.cpp.o

.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i

.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s

.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/input.cpp.s
.PHONY : input.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/main.cpp.s
.PHONY : main.cpp.s

merge.o: merge.cpp.o

.PHONY : merge.o

# target to build an object file
merge.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/merge.cpp.o
.PHONY : merge.cpp.o

merge.i: merge.cpp.i

.PHONY : merge.i

# target to preprocess a source file
merge.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/merge.cpp.i
.PHONY : merge.cpp.i

merge.s: merge.cpp.s

.PHONY : merge.s

# target to generate assembly for a file
merge.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/merge.cpp.s
.PHONY : merge.cpp.s

output.o: output.cpp.o

.PHONY : output.o

# target to build an object file
output.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/output.cpp.o
.PHONY : output.cpp.o

output.i: output.cpp.i

.PHONY : output.i

# target to preprocess a source file
output.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/output.cpp.i
.PHONY : output.cpp.i

output.s: output.cpp.s

.PHONY : output.s

# target to generate assembly for a file
output.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/output.cpp.s
.PHONY : output.cpp.s

parallel.o: parallel.cpp.o

.PHONY : parallel.o

# target to build an object file
parallel.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/parallel.cpp.o
.PHONY : parallel.cpp.o

parallel.i: parallel.cpp.i

.PHONY : parallel.i

# target to preprocess a source file
parallel.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/parallel.cpp.i
.PHONY : parallel.cpp.i

parallel.s: parallel.cpp.s

.PHONY : parallel.s

# target to generate assembly for a file
parallel.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/parallel.cpp.s
.PHONY : parallel.cpp.s

thr_safe_queue.o: thr_safe_queue.cpp.o

.PHONY : thr_safe_queue.o

# target to build an object file
thr_safe_queue.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/thr_safe_queue.cpp.o
.PHONY : thr_safe_queue.cpp.o

thr_safe_queue.i: thr_safe_queue.cpp.i

.PHONY : thr_safe_queue.i

# target to preprocess a source file
thr_safe_queue.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/thr_safe_queue.cpp.i
.PHONY : thr_safe_queue.cpp.i

thr_safe_queue.s: thr_safe_queue.cpp.s

.PHONY : thr_safe_queue.s

# target to generate assembly for a file
thr_safe_queue.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/thr_safe_queue.cpp.s
.PHONY : thr_safe_queue.cpp.s

unzip.o: unzip.cpp.o

.PHONY : unzip.o

# target to build an object file
unzip.cpp.o:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/unzip.cpp.o
.PHONY : unzip.cpp.o

unzip.i: unzip.cpp.i

.PHONY : unzip.i

# target to preprocess a source file
unzip.cpp.i:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/unzip.cpp.i
.PHONY : unzip.cpp.i

unzip.s: unzip.cpp.s

.PHONY : unzip.s

# target to generate assembly for a file
unzip.cpp.s:
	$(MAKE) -f CMakeFiles/Counting_words_in_file.dir/build.make CMakeFiles/Counting_words_in_file.dir/unzip.cpp.s
.PHONY : unzip.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Counting_words_in_file"
	@echo "... edit_cache"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... conveyor.o"
	@echo "... conveyor.i"
	@echo "... conveyor.s"
	@echo "... count_words.o"
	@echo "... count_words.i"
	@echo "... count_words.s"
	@echo "... decompress_list.o"
	@echo "... decompress_list.i"
	@echo "... decompress_list.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... merge.o"
	@echo "... merge.i"
	@echo "... merge.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... parallel.o"
	@echo "... parallel.i"
	@echo "... parallel.s"
	@echo "... thr_safe_queue.o"
	@echo "... thr_safe_queue.i"
	@echo "... thr_safe_queue.s"
	@echo "... unzip.o"
	@echo "... unzip.i"
	@echo "... unzip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

